### ISSUE TITLE
Updated the Wiki

### ISSUE THREAD

**Issue by ovY9jkhTEUpllGPJRrKU** [SizzlingStats/demboyz#13]
I added to the wiki in hopes that it could help those get a jump start on contributing or testing demboyz out. At least people in the CS:S GFL ZE server would love to extract audio or remove the voice chat for "TorchTV" (A bot that plays audio sounds on the mic when a command is entered by a user in-game).

I didn't know if I should have added this as an issue, but feel free to close this. I just wanted to update the contributors and was not sure what the best way to contact them was.

**Comment by SizzlingCalamari** [comment]
Thanks. Some info about the user lists and indices:

The user list from https://github.com/SizzlingStats/demboyz/wiki#user-list-no-indices looks like the output of the `status` command ingame. When a player connects to the server, they are assigned the next value in order starting at 0 and wrapping around 32767.

`fromClientIndex` in the voice data packet represents the client index of the voice data. This is going to be in the range of 0 to the max number of players.

The best way to find out the `fromClientIndex` of the voice data you want to exclude is just by listening to the audio clips.

**Comment by ovY9jkhTEUpllGPJRrKU** [comment]
## Error
`demboyz: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

## Description
I ran into an issue (fixed now) while running demboyz on Linux. It involved `$LD_LIBRARY_PATH` not being assigned, so it would output an error while loading shared libraries. Hopefully, those who want to run this locally through Linux will not find an issue with running `demboyz` after :).

## Solution
You can set `LD_LIBRARY_PATH` to include the current directory you are in (there is another path if you do `find . -name libsteam_api.so` in the demboyz directory).

```
// Sets current location as load library path also your previous LD_LIBRARY_PATH if you had any paths
export LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"
```

Information can be found here: https://stackoverflow.com/a/21173918/22330881

## How it is reproduced:
```
// Assume we are in demboyz
$ cd premake
$ ./gmake.sh
$ make
$ cd ../bin
$ chmod +x ./demboyz
$ ./demboyz
```

**Comment by SizzlingCalamari** [comment]
I'm reading that something like `-Wl,-rpath=$ORIGIN` might allow dynamic libs in the same folder as the executable to load by default. Play around with adding that to the premake and submit a pull request if you want.
