### ISSUE TITLE
fromClientIndex

### ISSUE THREAD

**Issue by jpfleischer** [SizzlingStats/demboyz#15]
Hi @SizzlingCalamari 
What is the significance of fromClientIndex?
https://github.com/SizzlingStats/demboyz/blob/995d19d540f37f6b08efee82c68e71264c9b4a70/demboyz/netmessages/svc_voicedata.cpp#L32

How to convert to username or steam id?
Thank you

**Comment by SizzlingCalamari** [comment]
fromClientIndex is the entity index of that client. Just an array index from 1 to MAX_PLAYERS. 

Demboyz doesn't currently parse player names or steam ids, so you'll need to try to find where they are stored. Dem_StringTables might be a good start. If you haven't seen it already, the source sdk is a good resource too.

**Comment by SizzlingCalamari** [comment]
```
    if (packet.cmd == dem_stringtables)
    {
        DemMsg::Dem_StringTables* stringTables = (DemMsg::Dem_StringTables*)packet.data;
        for (const DemMsg::Dem_StringTables::StringTable& table : stringTables->stringtables)
        {
            if (!strcmp(table.tableName.c_str(), "userinfo"))
            {
                for (DemMsg::Dem_StringTables::StringTableEntry& entry : table.entries)
                {
                    const char* nameUtf8 = (const char*)entry.data.begin();
                }
            }
        }
    }
```

Drop that in any StartCommandPacket override and you can see player names there. I'm guessing the index of table.entries is the entity index aka fromClientIndex. Use SVC_UpdateStringTable to track changes to the userinfo table.

**Comment by jpfleischer** [comment]
thank you very much.
i have implemented this in my fork.
