### ISSUE TITLE
[Question] Output to .log format

### ISSUE THREAD

**Issue by ldesgoui** [SizzlingStats/demboyz#8]
Hello,

I'd be interested in adding a .log format output to this tool, similar to what Logs.TF accepts as input file, has it been considered before? If so, what were the challenges that stopped from being implemented?

Thank you.

**Comment by SizzlingCalamari** [comment]
Hi,
Sounds good. It hasn't been considered before and I don't foresee any problems with implementing it. A simple version can probably be done as a derived class of IDemoWriter that listens for game event messages.

Do you have any specs of what you'd want to support?
