### ISSUE TITLE
How do I use the Voice Data Writer?

### ISSUE THREAD

**Issue by ip2k** [SizzlingStats/demboyz#9]
It looks like there's no current way within demboyz.cpp to have it spit out separate wavs for voice chat like voicewriter seems to support. I tried hacking in a wav enum for FileType and doing this:

```
else if (outputType == FileType::Wav)
    {
        char* FullPath = "C:/foo";
        writer = IDemoWriter::CreateVoiceDataWriter(FullPath);
    }
```

but that throws on voicedatawriter.cpp#250 with an assertion failure:

```
Assertion failed: !strcmp(voiceInit->voiceCodec, "vaudio_celt"), file C:\Users\root\Downloads\demboyz-master\demboyz\io\voicewriter\voicedatawriter.cpp, line 250
```

I don't really know C++ but I'm hoping to get some help here. The interface and implementation seem done, just looks like it needs to be wired in to be useable. This would be awesome if it worked. Thanks!

**Comment by SizzlingCalamari** [comment]
What's the value of voiceInit->voiceCodec when hitting that assert? I'm
assuming it's the steam voice codec which I do have some updated code to
support.

**Comment by jwestfall69** [comment]
Its the steam voice codec.

**Comment by SizzlingCalamari** [comment]
Thanks. Steam codec parsing is working on my end with some local changes. I'll have it up here in a day or so.

**Comment by SizzlingCalamari** [comment]
I just pushed some code that works for me on windows.

**Comment by jwestfall69** [comment]
I got it to compile ok, but its unhappy about steam init

```
Extracting voice data from mydemo.dem to mydir
SteamAPI_Init failed. Ensure Steam is running and logged in.
```
I'm definitely logged into steam on the box I'm running it on.

Some additional weirdness.  The code in main() is force changing the cwd to "..", which throws off the in/out locations supplied on the cli.

```
C:\Users\jwestfall\temp\demboyz mydemo.dem mydir
Working Directory: C:\Users\jwestfall
Error: Could not open input file
```
So its trying to look in C:\Users\jwestfall for mydemo.dem when its in the same dir I have demboyz.exe in.  You have to run it as demboyz temp\mydemo.dem mydir for it to fine the demo.

**Comment by jwestfall69** [comment]
I got the steam init issue fixed.  It was wanting the steam_appid.txt file

**Comment by SizzlingCalamari** [comment]
Good point about the chdir, I'm always using absolute paths when testing.
Will probably need to toss the appid txt in bin or something and only chdir
when in a debugger.

**Comment by SizzlingCalamari** [comment]
Should be fixed now. Removed the chdirs and found a debugdir setting for premake.

**Comment by jwestfall69** [comment]
Works great thanks!
